/**
 * Filmkritiken-Backend
 * Filmkritiken-Backend
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Film } from './film';


export interface FilmRequest { 
    film: Film;
    /**
     * Der Benutzer, der den Film vorgeschlagen hat.
     */
    von: string;
    /**
     * Datum nach ISO 8601 / EN 28601, an dem der Film besprochen wird / wurde.
     */
    besprochenam: string;
    /**
     * True, wenn noch Bewertungen abgegeben werden können.
     */
    bewertungoffen?: boolean;
}

