/**
 * Filmkritiken-Backend
 * Filmkritiken-Backend
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface FilmkritikenDetails { 
    beitragvon: string;
    /**
     * Datum nach ISO 8601 / EN 28601, an dem der Film besprochen wird / wurde.
     */
    besprochenam?: string;
}

